'use strict';

/**
 * Phase 3 Workflow Seed — 8 missing P0/P1 workflow definitions
 *
 * trigger_event               Department    Priority
 * ─────────────────────────── ───────────── ────────
 * breach_detected             Compliance    P0 (GDPR 72h obligation)
 * invoice_received            Finance       P1
 * budget_requested            Finance       P1
 * employee_offboarding        HR            P1
 * performance_review_submitted HR           P1
 * ticket_raised               Ops           P1
 * rule_change_proposed        Fraud         P1
 * blackout_requested          Revenue       P1
 */

exports.up = async (knex) => {
  const definitions = [

    // ── P0: GDPR Breach Response ──────────────────────────────────────────────
    {
      name:          'GDPR Breach Incident Response',
      department:    'compliance',
      trigger_event: 'breach_detected',
      description:   'Mandatory 72-hour GDPR breach response: DPO notified → legal review → regulator notification → remediation plan → close',
      status:        'active',
      version:       '1.0.0',
      created_by:    'system',
      approval_chain: JSON.stringify(['dpo', 'legal_manager', 'super_admin']),
      steps: JSON.stringify([
        {
          id:               'dpo_notify',
          name:             'DPO Immediate Notification',
          type:             'approval',
          assignee_role:    'dpo',
          sla_hours:        4,
          escalate_to_role: 'super_admin',
          on_approve:       'legal_review',
          on_reject:        null,
          on_timeout:       'legal_review',
          description:      'DPO must acknowledge the breach within 4 hours and begin severity assessment',
        },
        {
          id:               'legal_review',
          name:             'Legal Risk Assessment',
          type:             'approval',
          assignee_role:    'legal_manager',
          sla_hours:        8,
          escalate_to_role: 'super_admin',
          on_approve:       'regulator_notify',
          on_reject:        null,
          on_timeout:       'regulator_notify',
          description:      'Legal must assess notification obligations under GDPR Art.33/34, PDPL-KSA, and CCPA',
        },
        {
          id:               'regulator_notify',
          name:             'Regulator Notification (72h deadline)',
          type:             'action',
          assignee_role:    'dpo',
          sla_hours:        24,
          escalate_to_role: 'super_admin',
          on_approve:       'remediation_plan',
          on_reject:        null,
          on_timeout:       'super_admin_escalation',
          description:      'File Art.33 notification with supervisory authority if risk to individuals. Notify affected users if high risk (Art.34)',
        },
        {
          id:               'super_admin_escalation',
          name:             'Executive Escalation (SLA breach)',
          type:             'notification',
          assignee_role:    'super_admin',
          sla_hours:        2,
          escalate_to_role: 'super_admin',
          on_approve:       'remediation_plan',
          on_reject:        null,
          on_timeout:       null,
          description:      'Escalate to executive team — regulator notification deadline may be missed',
        },
        {
          id:               'remediation_plan',
          name:             'Remediation Plan & Sign-off',
          type:             'approval',
          assignee_role:    'super_admin',
          sla_hours:        72,
          escalate_to_role: 'super_admin',
          on_approve:       null,
          on_reject:        null,
          on_timeout:       null,
          description:      'COO/CTO sign off on technical and process remediation plan to prevent recurrence',
        },
      ]),
    },

    // ── P1: Finance — Invoice P2P ─────────────────────────────────────────────
    {
      name:          'Vendor Invoice Approval (P2P)',
      department:    'finance',
      trigger_event: 'invoice_received',
      description:   'Purchase-to-pay: vendor invoice logged → finance verify 3-way match → payment approved → paid',
      status:        'active',
      version:       '1.0.0',
      created_by:    'system',
      approval_chain: JSON.stringify(['finance_manager', 'cfo']),
      steps: JSON.stringify([
        {
          id:                    'finance_verify',
          name:                  'Finance 3-Way Match Verification',
          type:                  'approval',
          assignee_role:         'finance_manager',
          sla_hours:             48,
          escalate_to_role:      'super_admin',
          on_approve:            'cfo_approval',
          on_reject:             'vendor_query',
          on_timeout:            null,
          auto_approve_condition: { field: 'total_amount', op: 'lte', value: 5000 },
          description:           'Match invoice against PO and delivery confirmation. Auto-approve invoices ≤ SAR 5,000 with valid PO reference',
        },
        {
          id:               'vendor_query',
          name:             'Query Returned to Vendor',
          type:             'notification',
          assignee_role:    'finance_manager',
          sla_hours:        72,
          escalate_to_role: 'super_admin',
          on_approve:       'finance_verify',
          on_reject:        null,
          on_timeout:       null,
          description:      'Invoice has discrepancies — finance to contact vendor for correction',
        },
        {
          id:               'cfo_approval',
          name:             'CFO Payment Approval',
          type:             'approval',
          assignee_role:    'cfo',
          sla_hours:        24,
          escalate_to_role: 'super_admin',
          on_approve:       'payment_execute',
          on_reject:        null,
          on_timeout:       null,
          description:      'CFO approves payment release. Required for all invoices above SAR 5,000',
        },
        {
          id:               'payment_execute',
          name:             'Payment Released',
          type:             'action',
          assignee_role:    'finance_manager',
          sla_hours:        24,
          escalate_to_role: 'super_admin',
          on_approve:       null,
          on_reject:        null,
          on_timeout:       null,
          description:      'Finance processes bank transfer and marks invoice as paid. Upload payment confirmation.',
        },
      ]),
    },

    // ── P1: Finance — Budget Approval ─────────────────────────────────────────
    {
      name:          'Budget Approval',
      department:    'finance',
      trigger_event: 'budget_requested',
      description:   'Department budget request → Finance reviews → CFO approves → allocation confirmed',
      status:        'active',
      version:       '1.0.0',
      created_by:    'system',
      approval_chain: JSON.stringify(['finance_manager', 'cfo']),
      steps: JSON.stringify([
        {
          id:               'finance_review',
          name:             'Finance Review',
          type:             'approval',
          assignee_role:    'finance_manager',
          sla_hours:        72,
          escalate_to_role: 'super_admin',
          on_approve:       'cfo_approval',
          on_reject:        'dept_revision',
          on_timeout:       null,
          description:      'Finance validates budget against company plan and cash flow forecast',
        },
        {
          id:               'dept_revision',
          name:             'Revision Required',
          type:             'notification',
          assignee_role:    'dept_head',
          sla_hours:        120,
          escalate_to_role: 'super_admin',
          on_approve:       'finance_review',
          on_reject:        null,
          on_timeout:       null,
          description:      'Budget returned to department head with Finance comments for revision',
        },
        {
          id:               'cfo_approval',
          name:             'CFO Approval',
          type:             'approval',
          assignee_role:    'cfo',
          sla_hours:        48,
          escalate_to_role: 'super_admin',
          on_approve:       'allocation_confirm',
          on_reject:        'dept_revision',
          on_timeout:       null,
          description:      'CFO reviews and approves or rejects the budget allocation',
        },
        {
          id:               'allocation_confirm',
          name:             'Allocation Confirmed',
          type:             'notification',
          assignee_role:    'finance_manager',
          sla_hours:        24,
          escalate_to_role: 'super_admin',
          on_approve:       null,
          on_reject:        null,
          on_timeout:       null,
          description:      'Finance confirms allocation in the budgeting system and notifies department',
        },
      ]),
    },

    // ── P1: HR — Employee Offboarding ─────────────────────────────────────────
    {
      name:          'Employee Offboarding',
      department:    'hr',
      trigger_event: 'employee_offboarding',
      description:   'Resignation/termination → IT access revoke → final payroll → legal clearance → exit interview',
      status:        'active',
      version:       '1.0.0',
      created_by:    'system',
      approval_chain: JSON.stringify(['hr_manager', 'it_manager', 'finance_manager', 'legal_manager']),
      steps: JSON.stringify([
        {
          id:               'hr_acknowledge',
          name:             'HR Acknowledges Departure',
          type:             'approval',
          assignee_role:    'hr_manager',
          sla_hours:        24,
          escalate_to_role: 'super_admin',
          on_approve:       'it_access_revoke',
          on_reject:        null,
          on_timeout:       null,
          description:      'HR confirms last working day, notice period served, and triggers offboarding checklist',
        },
        {
          id:               'it_access_revoke',
          name:             'IT Access Revocation',
          type:             'approval',
          assignee_role:    'it_manager',
          sla_hours:        8,
          escalate_to_role: 'super_admin',
          on_approve:       'payroll_final',
          on_reject:        null,
          on_timeout:       null,
          description:      'IT revokes all system access: email, VPN, admin panels, cloud consoles, Slack, GitHub on last working day',
        },
        {
          id:               'payroll_final',
          name:             'Final Payroll Processing',
          type:             'approval',
          assignee_role:    'finance_manager',
          sla_hours:        72,
          escalate_to_role: 'super_admin',
          on_approve:       'legal_clearance',
          on_reject:        null,
          on_timeout:       null,
          description:      'Finance calculates final pay: salary, accrued leave, GOSI settlement, deductions. Issues end-of-service certificate.',
        },
        {
          id:               'legal_clearance',
          name:             'Legal Clearance',
          type:             'approval',
          assignee_role:    'legal_manager',
          sla_hours:        48,
          escalate_to_role: 'super_admin',
          on_approve:       'exit_interview',
          on_reject:        null,
          on_timeout:       null,
          description:      'Legal confirms NDA obligations, IP assignment, non-compete if applicable, and issues clearance letter',
        },
        {
          id:               'exit_interview',
          name:             'Exit Interview & Close',
          type:             'action',
          assignee_role:    'hr_manager',
          sla_hours:        72,
          escalate_to_role: 'super_admin',
          on_approve:       null,
          on_reject:        null,
          on_timeout:       null,
          description:      'HR conducts exit interview, files feedback, archives employee record, updates org chart',
        },
      ]),
    },

    // ── P1: HR — Performance Review ───────────────────────────────────────────
    {
      name:          'Quarterly Performance Review',
      department:    'hr',
      trigger_event: 'performance_review_submitted',
      description:   'Employee self-review → manager review → calibration → HR archive',
      status:        'active',
      version:       '1.0.0',
      created_by:    'system',
      approval_chain: JSON.stringify(['manager', 'hr_manager']),
      steps: JSON.stringify([
        {
          id:               'manager_review',
          name:             'Manager Review',
          type:             'approval',
          assignee_role:    'manager',
          sla_hours:        120,
          escalate_to_role: 'hr_manager',
          on_approve:       'calibration',
          on_reject:        'employee_revision',
          on_timeout:       null,
          description:      'Manager reviews employee self-assessment, adds ratings and comments on all competencies',
        },
        {
          id:               'employee_revision',
          name:             'Employee Revision Requested',
          type:             'notification',
          assignee_role:    'employee',
          sla_hours:        48,
          escalate_to_role: 'hr_manager',
          on_approve:       'manager_review',
          on_reject:        null,
          on_timeout:       null,
          description:      'Manager has requested the employee clarify or expand their self-assessment',
        },
        {
          id:               'calibration',
          name:             'HR Calibration',
          type:             'approval',
          assignee_role:    'hr_manager',
          sla_hours:        72,
          escalate_to_role: 'super_admin',
          on_approve:       'archive',
          on_reject:        'manager_review',
          on_timeout:       null,
          description:      'HR reviews for calibration consistency across the department, applies rating normalization if needed',
        },
        {
          id:               'archive',
          name:             'Archive & Notify Employee',
          type:             'action',
          assignee_role:    'hr_manager',
          sla_hours:        24,
          escalate_to_role: 'super_admin',
          on_approve:       null,
          on_reject:        null,
          on_timeout:       null,
          description:      'HR archives review, updates performance history, notifies employee of outcome',
        },
      ]),
    },

    // ── P1: Ops — Support Ticket SLA ──────────────────────────────────────────
    {
      name:          'Support Ticket SLA Tracking',
      department:    'ops',
      trigger_event: 'ticket_raised',
      description:   'Support ticket raised → AI triaged → assigned → SLA tracked → resolved → customer notified',
      status:        'active',
      version:       '1.0.0',
      created_by:    'system',
      approval_chain: JSON.stringify(['support_agent', 'ops_manager']),
      steps: JSON.stringify([
        {
          id:               'triage_assign',
          name:             'Triage & Assign',
          type:             'approval',
          assignee_role:    'ops_manager',
          sla_hours:        2,
          escalate_to_role: 'super_admin',
          on_approve:       'resolve',
          on_reject:        null,
          on_timeout:       null,
          description:      'AI triage runs automatically. Ops manager confirms priority, category, and assignee',
        },
        {
          id:               'resolve',
          name:             'Resolution',
          type:             'approval',
          assignee_role:    'support_agent',
          sla_hours:        24,
          escalate_to_role: 'ops_manager',
          on_approve:       'customer_notify',
          on_reject:        null,
          on_timeout:       null,
          description:      'Support agent resolves the ticket. For high/critical: 4h SLA applies. For medium: 24h. For low: 72h.',
        },
        {
          id:               'customer_notify',
          name:             'Customer Notification',
          type:             'action',
          assignee_role:    'support_agent',
          sla_hours:        2,
          escalate_to_role: 'ops_manager',
          on_approve:       null,
          on_reject:        null,
          on_timeout:       null,
          description:      'Send resolution confirmation to customer with summary of action taken and CSAT survey link',
        },
      ]),
    },

    // ── P1: Fraud — Rule Change Approval ──────────────────────────────────────
    {
      name:          'Fraud Rule Change Approval',
      department:    'fraud',
      trigger_event: 'rule_change_proposed',
      description:   'Risk signal → analyst proposes rule change → Risk Lead approves → deployed → monitored',
      status:        'active',
      version:       '1.0.0',
      created_by:    'system',
      approval_chain: JSON.stringify(['risk_lead', 'super_admin']),
      steps: JSON.stringify([
        {
          id:               'risk_lead_review',
          name:             'Risk Lead Review',
          type:             'approval',
          assignee_role:    'risk_lead',
          sla_hours:        24,
          escalate_to_role: 'super_admin',
          on_approve:       'impact_assessment',
          on_reject:        null,
          on_timeout:       null,
          description:      'Risk Lead reviews proposed rule: condition logic, action (flag/block/review), severity, false-positive risk',
        },
        {
          id:               'impact_assessment',
          name:             'Impact Assessment',
          type:             'approval',
          assignee_role:    'super_admin',
          sla_hours:        24,
          escalate_to_role: 'super_admin',
          on_approve:       'deploy',
          on_reject:        null,
          on_timeout:       null,
          description:      'Platform Admin reviews rule for potential impact on legitimate bookings, especially Hajj/Umrah customers',
        },
        {
          id:               'deploy',
          name:             'Deploy & Monitor',
          type:             'action',
          assignee_role:    'risk_lead',
          sla_hours:        8,
          escalate_to_role: 'super_admin',
          on_approve:       null,
          on_reject:        null,
          on_timeout:       null,
          description:      'Risk Lead activates rule, monitors false-positive rate for 48h, documents any customer impact',
        },
      ]),
    },

    // ── P1: Revenue — Blackout Period Approval ────────────────────────────────
    {
      name:          'Revenue Blackout Period Approval',
      department:    'revenue',
      trigger_event: 'blackout_requested',
      description:   'Ops/supply signals → Revenue sets blackout → Finance notified → lifted on schedule',
      status:        'active',
      version:       '1.0.0',
      created_by:    'system',
      approval_chain: JSON.stringify(['revenue_manager', 'cfo']),
      steps: JSON.stringify([
        {
          id:               'revenue_review',
          name:             'Revenue Manager Review',
          type:             'approval',
          assignee_role:    'revenue_manager',
          sla_hours:        8,
          escalate_to_role: 'super_admin',
          on_approve:       'finance_notify',
          on_reject:        null,
          on_timeout:       null,
          description:      'Revenue Manager validates blackout rationale: supply constraint, demand surge, or strategic hold',
        },
        {
          id:               'finance_notify',
          name:             'Finance Notification',
          type:             'approval',
          assignee_role:    'cfo',
          sla_hours:        24,
          escalate_to_role: 'super_admin',
          on_approve:       'activate',
          on_reject:        null,
          on_timeout:       'activate',
          description:      'CFO acknowledges revenue impact of blackout period. CFO approval required if projected loss > SAR 50,000',
        },
        {
          id:               'activate',
          name:             'Blackout Activated',
          type:             'action',
          assignee_role:    'revenue_manager',
          sla_hours:        4,
          escalate_to_role: 'super_admin',
          on_approve:       null,
          on_reject:        null,
          on_timeout:       null,
          description:      'Revenue Manager confirms blackout is active in pricing engine. Sets lift date in system.',
        },
      ]),
    },

  ];

  for (const def of definitions) {
    await knex.raw(`
      INSERT INTO workflow_definitions
        (name, department, trigger_event, description, status, version, created_by, approval_chain, steps)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
      ON CONFLICT (trigger_event)
      DO NOTHING
    `, [
      def.name, def.department, def.trigger_event, def.description,
      def.status, def.version, def.created_by,
      def.approval_chain, def.steps,
    ]);
  }
};

exports.down = async (knex) => {
  const events = [
    'breach_detected', 'invoice_received', 'budget_requested',
    'employee_offboarding', 'performance_review_submitted',
    'ticket_raised', 'rule_change_proposed', 'blackout_requested',
  ];
  await knex('workflow_definitions').whereIn('trigger_event', events).del();
};
